on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - run: sudo apt-get update
          - run: sudo apt-get install --no-install-recommends -y biber latexmk lmodern texlive-bibtex-extra texlive-latex-extra texlive-science
          - uses: actions/checkout@v2
          - run: make
